### PR TITLE
Bump Eigen version requirement to 3.3

### PR DESCRIPTION
**Pull request by khumba**
Eigen 3.3 is the first version to include Eigen3Config.cmake and
UseEigen3.cmake, which are needed for EIGEN3_USE_FILE.

----

With Eigen 3.2.8 for example, CMake aborts (presumably because EIGEN3_USE_FILE is undefined):

    -- Now adding packages
    CMake Error at SWIG_CGAL/Point_set_processing_3/CMakeLists.txt:6 (include):
      include called with wrong number of arguments.  include() only takes one
      file.
    
    
    CMake Error at CMakeLists.txt:149 (include):
      include called with wrong number of arguments.  include() only takes one
      file.
    
    
    -- Configuring incomplete, errors occurred!

CMakeLists.txt:149: (line number's off because I edited to build for C++11)

    include( ${EIGEN3_USE_FILE} )

SWIG_CGAL/Point_set_processing_3/CMakeLists.txt:6:

    include( ${EIGEN3_USE_FILE} )

Alternatively, it might not be too hard to be compatible with the old `FindEigen3.cmake`.

Eigen 3.3 is in beta now and I haven't tested this against e.g. the beta package that Debian has in testing.  Not sure who else is shipping 3.3; Gentoo and apparently Fedora are on 3.2.

### CODE REVIEW

**Comment by sloriot** [comment]
CGAL is shipping a FindEigen3.cmake which is setting these variables. Do you have another FIndEigen3.cmake in a cmake module path that override CGAL's?

**Comment by khumba** [comment]
Actually yes, Eigen's.  I wasn't aware that CGAL has that module as well.  Eigen (3.2 included) ships a FindEigen3.cmake, and Gentoo packaging prefers that one over CGAL's, choosing not to install, or from the looks of it even build CGAL with, CGAL's own FindEigen3.cmake.

I'm not sure I can comment further, as I don't know the reason CGAL ships these files.  It would be nice if upstream's modules were sufficient.  The name collision is unfortunate, but this is just an unrelated build failure I hit and it's easy to work around, so if you're happy with things as they are, feel free to close.

**Comment by lrineau** [comment]
We should add `set(EIGEN3_USE_FILE "UseEigen3")` in the common file `cmake/modules/CGAL_Common.cmake`. That way the CMake scripts would be compatible with both `Findeigen3` version.

**Comment by sloriot** [comment]
See #1136

**Comment by khumba** [comment]
This should do the trick.  Thanks again!

@sloriot, as a follow-up, we've decided that your suggestion in private email to use CGLAB (if it's still called that?) was right; while it works, the Scilab interface generated by SWIG is too cumbersome (e.g. manual memory management everywhere), and would be a lot more work than just updating the Scilab 4 Arrangement_2d CGLAB extensions we already have (which actually is basically done now and only took a few days).

We would like to make our changes available upstream, if you think they're suitable, so I'll open a PR over there soon ([here](https://forge.scilab.org/index.php/p/cgal/) looks to be the current repo).

**Comment by sloriot** [comment]
Scilab extension are managed by the scilab team now. I think is it located [here](https://atoms.scilab.org/toolboxes/cglab)

**Pull request closed without merging**
