### PR TITLE
Classification bindings

### PR DESCRIPTION
**Pull request by sgiraudot**
This PR adds:
- bindings for Classification of point sets (mesh could be integrated later but it'd be nice to have Surface Mesh before that), including example in both Python and Java
- TBB support for PSP and classification
- LASlib support for Point Set IO

### CODE REVIEW

**Comment by lrineau** [comment]
It does not seems to build well, on Linux (in Travis), or on Windows (in Github Actions).

**Comment by sgiraudot** [comment]
The error message is wrong (I just fixed it), but I'm guessing the problem is the following: Boost Serialization and/or Boost IO Streams are not installed, which means Classification bindings are not compiled. But then, the examples of classification in Java/Python are still tested and obviously fail because the binding is missing.

Serialization and IO Streams should be installed on the testing platforms (and I don't know if it's useful to filter the tests out if these are not installed).

**Comment by sloriot** [comment]
The [doc](https://docs.python.org/2/library/modulefinder.html) says to do something like:
```
try:
    import baconhameggs
except ImportError:
    pass
```

**Comment by sloriot** [comment]
What is the status of this PR? shall I merge or do you want to try the `ImportError` mentioned above?

**Comment by sgiraudot** [comment]
You can merge it, I don't think it's useful to make the configuration of tests robust to missing dependencies considering we want to test the whole thing (with all dependencies) and we control the test environment.

**Comment by lrineau** [comment]
I agree. What is more, there might be other issues than missing dependencies, that could trigger the `ImportError` exception in the tests, and we want to know about those issues if they occur.

**Pull request merged**
