### PR TITLE
CMake: Using new way of finding Python

### PR DESCRIPTION
**Pull request by thopiekar**
Goals:
 * Getting a rid of line within the CMake files here, which are in CMake's FindPython module.
 * Getting consistent findings across interpreter, libraries and other files:
```
-- Found Threads: TRUE  
-- BUILD_RUBY is set to OFF: no CGAL-bindings for Ruby will be generated.
-- Found PythonInterp: /<<PKGBUILDDIR>>/python2.7  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.2rc1") 
-- BUILD_JAVA is set to OFF: no CGAL-bindings for Java will be generated.
-- Found Python libs.
-- CGAL-SWIG Python files and libraries will be written in /<<PKGBUILDDIR>>/build-python2.7/build-python/CGAL.
-- Now adding packages
```
(with the previous code)

Requires CMake 3.12+ at the latest.

Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com> (github: thopiekar)

### CODE REVIEW

**Comment by thopiekar** [comment]
I'm done with my changes,  but I think the CI environments need to be updated, too.

**Comment by sloriot** [comment]
What is the goal of this PR?

**Comment by thopiekar** [comment]
@sloriot Added more info to the description of the PR.

I have the suspect that the upgraded setup of Ubuntu Xenial with CMake >3.12.x and other software makes the build run, but the test fail here.
Running the codebase on a clean Ubuntu Eoan image works fine.

**Comment by maxGimeno** [comment]
hello @thopiekar and thanks for the PR ! 
Could you please add me as a collabaorator so I can edit your PR and start the process of integration ? I'll have to edit stuff for the CI and cancel some unwanted caps modifications of yours, but I jeust tested the cmake logic and it seems good to me.

**Comment by thopiekar** [comment]
Hello @maxGimeno !

Sure! I'm just wondering why you are not able to make edits already. The checkbox is already abled to allow maintainers to make edits:
image

Anyway, I sent you the invite! :wink: Let me know if there is something you need still!

Cheers!
- Thomas

**Comment by lrineau** [comment]
I just promoted @maxGimeno and @sgiraudot as "maintainer" of this repository. It was not the case before.

**Comment by maxGimeno** [comment]
I removed some unwanted diff (all the set( instead of SET ( that enlarges the diff and the risk of having conflicts) and the add_test that you added in classification. This is already done in the global CMake and I think it was the reason why the CI was unhappy.
Also I added some fixes to bugs we had in the install process.

**Comment by maxGimeno** [comment]
Integrated through #162

**Pull request closed without merging**
