### PR TITLE
Adding Shape_Detection_3

### LINKED ISSUE #131: Missing bindings for Shape_detection_3
Hello everybody,

are there any plans or even work in progress around for Shape_detection_3 bindings?
Would be glad to use these bindings here to process some point clouds.

Thanks!

### PR DESCRIPTION
**Pull request by thopiekar**
I moved all the files into the correct location, while re-migrating the commits from @CodyFagley correctly. Also corrected some includes, but the following work still needs to be done:
 - [ ] Clearification what needs to be included in the CI test
 - [ ] Adding the actual test
 - [ ] Adding missing functions and fixing bugs
 - [ ] Whatever else comes up

Follow up of https://github.com/CGAL/cgal-swig-bindings/pull/138

Fixes #131

### CODE REVIEW

**Comment by thopiekar** [comment]
@lrineau My intention is to get this example running in Python:
https://doc.cgal.org/5.0/Shape_detection/index.html#title6
Therefore, I can imagine, that you expect that nearly identical lines will work on a converted script, too, right?

Are there any other things you see in the code that needs to be discussed?

Thanks!

**Comment by lrineau** [comment]
I will let Simon Giraudot (@sgiraudot) discuss about that with you. He is one of the authors of the CGAL Shape Detection package, and recently got interested in the Python bindings for that package.

**Comment by sgiraudot** [comment]
Bindings for shape detection were added just last week (see https://github.com/CGAL/cgal-swig-bindings/pull/145 and [the Python example](https://github.com/CGAL/cgal-swig-bindings/blob/master/examples/python/Shape_detection_example.py) that comes with it).

**Comment by lrineau** [comment]
Hi @thopiekar @CodyFagley, I am sorry for the bad timing. You have invested time in those bindings, and at the same time one of the CGAL author did the same job.

I am probably the one responsible for that. I should have seen that you were working on the same topic.

Here is my suggestion, now: please review the patch from PR #145, and maybe you can see possible improvements, based on your own work. Let us know if the bindings added by #145 suit your needs. In previous PR #138, you reported 
memory leaks and other issues. Are they now fixed if you use the bindings added by PR #145?

**Pull request closed without merging**
