### PR TITLE
Fix Travis for MacOS

### PR DESCRIPTION
**Pull request by maxGimeno**
Update XCode to v11.2

### CODE REVIEW

**Comment by lrineau** [comment]
It seems there is a syntax error in the Travis file, now:
https://travis-ci.org/CGAL/cgal-swig-bindings/requests?utm_medium=notification&utm_source=github_status

**Comment by lrineau** [comment]
https://docs.brew.sh/Homebrew-and-Python

The default `python` is `python2`.

**Comment by sloriot** [comment]
Looks like we are left with clang segfaulting and a timeout.

**Comment by maxGimeno** [comment]
To address the remainings problems, @lrineau and I decided to stop testing 4.13 and 4.14 for macOS.

**Comment by lrineau** [comment]
Thanks @sloriot and @maxGimeno for that nice work!

**Pull request merged**
