### PR TITLE
Fixes with CGAL-5.0-dev

### PR DESCRIPTION
**Pull request by maxGimeno**
Fixes bugs in master.

### CODE REVIEW

**Comment by maxGimeno** [comment]
I think I broke Java....

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [May 17, 2019, 9:56 AM GMT+2](https://github.com/CGAL/cgal-swig-bindings/pull/125#issuecomment-493359853 "2019-05-17T07:56:08Z - Replied by Github Reply Comments"):
> I think I broke Java....

Actually, you also broke Python, but cgal-swig-bindings does not have Python tests for all classes: Travis only checks that the Python bindings compile, and not that they are fully usable.

**Comment by maxGimeno** [comment]
When I use the macros to define iterators, it does not define iteraators,types in swig do not correspond to types in c++, nothing works anywhere, i give up.

**Comment by lrineau** [comment]
@maxGimeno Now we are back to Travis compilation error, about AABB_tree, with CGAL-5.0-dev (master):
https://travis-ci.org/CGAL/cgal-swig-bindings/jobs/533789716#L6214
```
.../cgal-swig-bindings/SWIG_CGAL/AABB_tree/AABB_tree.h:177:76: error: no matching function for call to ‘std::pair<Object, SWIG_Polyhedron_3::CGAL_Facet_handle<CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3> > >::pair(std::pair<boost::variant<CGAL::Point_3<CGAL::Epick>, CGAL::Segment_3<CGAL::Epick> >, CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_max_base_with_id<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_with_id_3>, std::allocator<int> >, CGAL::Boolean_tag<false>, long unsigned int> > >, std::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_max_base_with_id<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_with_id_3>, std::allocator<int> >, CGAL::Boolean_tag<false>, long unsigned int> > > > > >&)’
       return Optional_object_and_primitive_id(Object_and_primitive_id(*res));
                                                                            ^
```

**Comment by lrineau** [comment]
Now the error is:
```
/home/travis/build/CGAL/cgal-swig-bindings/SWIG_CGAL/AABB_tree/AABB_tree.h:177:76: error: no matching function for call to ‘std::pair<Object, SWIG_Polyhedron_3::CGAL_Facet_handle<CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3> > >::pair(std::pair<boost::variant<CGAL::Point_3<CGAL::Epick>, CGAL::Segment_3<CGAL::Epick> >, CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_max_base_with_id<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_with_id_3>, std::allocator<int> >, CGAL::Boolean_tag<false>, long unsigned int> > >, std::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_max_base_with_id<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_with_id_3>, std::allocator<int> >, CGAL::Boolean_tag<false>, long unsigned int> > > > > >&)’
       return Optional_object_and_primitive_id(Object_and_primitive_id(*res));
```
https://travis-ci.org/CGAL/cgal-swig-bindings/jobs/533789716#L6214

With g++-5. It means that it cannot find the constructor of:
```c++
std::pair<
  Object,
  SWIG_Polyhedron_3::CGAL_Facet_handle<CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3> >
>
```
from a reference to:
```c++
std::pair<
  boost::variant<CGAL::Point_3<CGAL::Epick>, CGAL::Segment_3<CGAL::Epick> >,
  CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_max_base_with_id<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_with_id_3>, std::allocator<int> >, CGAL::Boolean_tag<false>, long unsigned int> > >, std::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_max_base_with_id<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_with_id_3>, std::allocator<int> >, CGAL::Boolean_tag<false>, long unsigned int> > > > >
>
```

g++-5 STL does have that constructor in `/usr/include/c++/5/bits/stl_pair.h`:
```c++
    121       template<class _U1, class _U2, class = typename
    122                enable_if<__and_<is_convertible<const _U1&, _T1>,
    123                                 is_convertible<const _U2&, _T2>>::value>::type>
    124         constexpr pair(const pair<_U1, _U2>& __p)
    125         : first(__p.first), second(__p.second) { }
```
but for some reason the `enable_if` rejects the overload.

**Comment by lrineau** [comment]
Now the error seems completely different.

**Comment by lrineau** [comment]
Congratulation: Travis tests passed!

**Comment by maxGimeno** [comment]
Finally !

**Pull request merged**
