### PR TITLE
Changes for 5.3+

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by sloriot** [comment]
@maxGimeno do you know how to fix the CI?

**Comment by maxGimeno** [comment]
There's a lot of different errors on different test machines. One is missing boost, one is testing an old tbb code that doesn't exist anymore, some are experiencing segfaults... 
It's not the CI that is broken, it's a little of everything.

**Comment by maxGimeno** [comment]
Problematic situation for boost : 
https://github.com/actions/virtual-environments/issues/2667

**Comment by lrineau** [comment]
> Problematic situation for boost :
> [actions/virtual-environments#2667](https://github.com/actions/virtual-environments/issues/2667)

Then the test script should install Boost, like the other dependencies.

**Comment by lrineau** [comment]
Same for this PR, should we merge it, and then see in another PR what we can improve?

**Pull request merged**
