### PR TITLE
Allow more java tests

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by sloriot** [comment]
I think only one call to cmake in the travis config file is sufficient to get Java and Python compiled. Any reason why you have two?

**Comment by xantares** [comment]
There's one for Python2+Java, and another for just Python3.

**Comment by sloriot** [comment]
Right, I was confused by the fact that the java tests were ran twice. I guess the addition of test should be conditional to the value of BUILD_JAVA and BUILD_PYTHON.

**Comment by xantares** [comment]
that's easy to solve

**Comment by lrineau** [comment]
@xantares 

Instead of using apt commands, and custom CMake options, you might want to use the pre-defined python and java environments provided by Travis CI:
- [Testing Against Multiple JDKs]
- [Choosing Python versions to test against]

[Testing Against Multiple JDKs]: https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
[Choosing Python versions to test against]: https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against

That will split the build job into several build jobs.

You can add a [build matrix], to avoid cross-testing all python versions with all java versions.

[build matrix]: https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

**Comment by xantares** [comment]
That should be doable, it would allow to test more python/java versions. Maybe in another PR. My main concern were python2/3, and I'm fine for now.

**Pull request merged**
